### ISSUE TITLE
US5: As a runner, I want to listen to a playlist that contains songs based on the pace preference I have listed to help me reach my running goals.

### ISSUE THREAD

**Issue by adityaganesh0309** [aaronto0705/Tempo#16]
User Story: As a runner, I want to listen to a playlist that contains songs based on the pace preference I have listed to help me reach my running goals.

I should be able to stream music directly from Spotify while still on the Tempo app that is DIRECTLY related to an either a fixed, increasing, or decreasing running pace. I can set the pace preference before my run and the music will remain relevant to that pace. For increasing and decreasing pace, songs will change by a constant BPM factor.

T-Shirt Size Estimation: M

**Comment by aaronto0705** [comment]
Working on adding screen or decreasing wait time on this.
